---

- name: apt | perf packages install
  apt:
    name:
      - linux-tools-{{ ansible_kernel }}
      - perl
      - git
      - systemtap
## not available on trusty
#      - ktap
    state: present
    update_cache: yes

- name: apt | add debug symbols repository
  template:
    src: ddebs.list.j2
    dest: /etc/apt/sources.list.d/ddebs.list
    mode: '0644'
    backup: yes
  register: dbgrep

- name: apt | add debug symbol archive signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
    state: present
  with_items:
    - 428D7C01
    - C8CAB6595FDFF622

- name: apt | update cache
  apt: update_cache=yes
  when: dbgrep.changed

- name: apt | ensure few debug packages are present
  apt:
    name: "{{ flamegraph_dbg_pkgs | default([]) }}"
    state: present
