---

- name: apt | perf packages install
  apt:
    name:
      - linux-tools-{{ ansible_kernel }}
      - perl
      - git
      - systemtap
      ## not available on trusty
      # - ktap
    state: present
    update_cache: yes

- name: apt | add debug symbol archive signing key
  apt_key:
    data: "{{ lookup('file', 'pgp-0x' + item|string + '.asc') }}"
    state: present
  with_items:
    - 2512191fef8729d6e5af414decdcad72428d7c01
    - C8CAB6595FDFF622

- name: apt | add debug symbols repository
  template:
    src: ddebs.list.j2
    dest: /etc/apt/sources.list.d/ddebs.list
    mode: '0644'
    backup: yes
  notify:
    - apt update cache

- name: Flush handlers
  meta: flush_handlers

- name: apt | ensure few debug packages are present
  apt:
    name: "{{ flamegraph_dbg_pkgs | default([]) }}"
    state: present
