---
## http://www.brendangregg.com/flamegraphs.html
## http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html

- include: debian.yml
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (flamegraph_install is defined and flamegraph_install)

- include: redhat.yml
  when: (ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and (flamegraph_install is defined and flamegraph_install)

- git: repo=https://github.com/brendangregg/FlameGraph
       dest="{{ flamegraph_root }}"
  when: (flamegraph_install is defined and flamegraph_install)

- include: flamegraph-capture.yml
  when: (flamegraph_capture is defined and flamegraph_capture) and (ansible_virtualization_type is not defined or not (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "kvm"))

- debug: msg="Not running flamegraph capture as container"
  when: not (ansible_virtualization_type is not defined or not (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "kvm"))

